"""Add source_email_id to job_postings

Revision ID: 142f96275763
Revises: 
Create Date: 2025-02-19 04:01:19.814423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142f96275763'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('education', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('achievements', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('source_email_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'emails', ['source_email_id'], ['id'])
    op.create_foreign_key(None, 'emails', 'email_threads', ['thread_id'], ['thread_id'])
    op.add_column('job_postings', sa.Column('source_email_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_postings', 'emails', ['source_email_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'source_email_id')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'source_email_id')
    op.drop_column('candidates', 'achievements')
    op.drop_column('candidates', 'education')
    # ### end Alembic commands ###
